#!/bin/sh
#$Id$
#Copyright (c) 2020 Pierre Pronchery <khorben@defora.org>
#This file is part of DeforaOS Devel scripts
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions
#are met:
#1. Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
#2. Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
#THIS SOFTWARE IS PROVIDED BY THE EDGEBSD PROJECT AND CONTRIBUTORS
#``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
#TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
#PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
#BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#POSSIBILITY OF SUCH DAMAGE.



#variables
#executables
GIT="git"
GIT_CLONE="$GIT clone -q"
GIT_FETCH="$GIT fetch -q"
GIT_RESET="$GIT reset -q"
GIT_MIRROR=
GIT_REMOTE="origin"
#settings
GIT_HOME="$HOME/repositories"
PREFIX="/usr/local"
PROGNAME="deforaos-job-git-mirror"
SYSCONFDIR="$PREFIX/etc"
#load local settings
[ -f "$SYSCONFDIR/DeforaOS/$PROGNAME.conf" ] &&
	. "$SYSCONFDIR/DeforaOS/$PROGNAME.conf"
[ -f "$HOME/.config/DeforaOS/$PROGNAME.conf" ] &&
	. "$HOME/.config/DeforaOS/$PROGNAME.conf"


#functions
#git_mirror
_git_mirror()
{
	repository="$1"
	mirror="$GIT_MIRROR${repository}.git"

	if [ ! -d "$mirror" ]; then
		#clone the repository
		$GIT_CLONE "$GIT_HOME/${repository}.git" "$mirror"
		if [ $? -ne 0 ]; then
			echo "$repository: Could not create mirror" 1>&2
			continue
		fi
	fi
	#mirror the repository
	(cd "$mirror" &&
		$GIT_FETCH "$GIT_REMOTE" &&
		$GIT_RESET --hard "$GIT_REMOTE/$branch")	|| return 2
}


#usage
_usage()
{
	echo "Usage: $PROGNAME repository" 1>&2
	return 1
}


#main
while getopts "O:" name; do
	case "$name" in
		O)
			export "${OPTARG%%=*}"="${OPTARG#*=}"
			;;
		*)
			_usage
			exit $?
			;;
	esac
done
shift $((OPTIND - 1))
if [ $# -ne 1 ]; then
	_usage
	exit $?
fi
_git_mirror "$1"
